stages:
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

build_windows_x64:
  stage: build
  tags:
    - WindowsBuilder
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never
  script:
    - cd native
    - cmd.exe /c "build-windows.bat x64"
  artifacts:
    paths:
      - native/build/Release/*

build_windows_arm64:
  stage: build
  tags:
    - WindowsBuilder
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never
  script:
    - cd native
    - cmd.exe /c "build-windows.bat arm64"
  artifacts:
    paths:
      - native/build/Release/*

build_terraform:
  stage: build
  tags:
    - LinuxBuilder
  variables:
    TF_VAR_release_version: $CI_COMMIT_TAG
    TF_VAR_cf_r2_account_id: $CF_R2_ACCOUNT_ID
    TF_VAR_cf_r2_access_key_id: $CF_R2_ACCESS_KEY_ID
    TF_VAR_cf_r2_secret_access_key: $CF_R2_SECRET_ACCESS_KEY
    TF_VAR_cf_r2_bucket: $CF_R2_BUCKET
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never
  script:
    - cd native
    - terraform init -input=false
    - terraform apply -auto-approve -input=false
